### ISSUE TITLE
[FEATURE] Conversion operators for tuple

### ISSUE THREAD

**Issue by groundswellaudio** [jfalcou/ofw#17]
It would be nice to have generic conversions operators for `kumi::tuple` to allow construction from those tuples. A simple approach would be something like : 

```cpp
template <class... Ts>
struct tuple {

template <class... Us>
    requires (std::is_constructible_v<Ts, Us> && ...)
explicit(not (std::is_convertible_v<Ts, Us> && ...)) constexpr operator tuple<Us...> ();

};
```

Furthermore, it might be desirable to have a entirely generic conversion to a type T, whose only requirements is that T is constructible from Ts... : 

```cpp
template <class T>
    requires std::is_constructible_v<T, Ts...>
explicit(not (std::is_convertible_v<Ts, Us> && ...)) constexpr operator T();
```

This would enable some pretty cool interoperability with every other containers (or types, in general) out there. Hopefully, it doesn't lead to some surprising code.

**Comment by jfalcou** [comment]
The tuple conversion is working and seems OK.

I think the explicit condition is wrong for the Type one though. Shouldn't it be explicit all along.

**Comment by groundswellaudio** [comment]
```cpp
template<typename... Ts> template<typename... Us>
  requires(
      std::is_constructible_v<Ts, Us> &&...) constexpr tuple<Ts...>::operator tuple<Us...>() const
  {
    return [&]<std::size_t... I>(std::index_sequence<I...>)
    {
      return make_tuple(Us(detail::get_leaf<I>(impl))...);
    }
    (std::make_index_sequence<sizeof...(Ts)>());
  }
```

There is a problem here, this doesn't work for converting to a tuple of references. 

This should work : 

```cpp
template<typename... Ts> template<typename... Us>
  requires(
      std::is_constructible_v<Ts, Us> &&...) constexpr tuple<Ts...>::operator tuple<Us...>() const
  {
      return apply( [] (auto&&... elems) { return tuple<Ts...>{ elems... }; }, *this );
  }
```

Also, apparently std::is_convertible_v<T, T&> is always false, so perhaps the explicit condition should take that into account if this is something that you want to support. 

> I think the explicit condition is wrong for Type one though. Shouldn't it be explicit all along?

Oh yeah, the second snippet is non-sensical. I wouldn't make it explicit though, because this would prevent doing something like : 

```cpp
struct foo {
    foo(double, int){}
};

struct my_type {
    foo a;
    foo b;
};

kumi::tuple<double, int> tpl;

my_type container { tpl, tpl };
```

Which i find pretty cool. 

Instead, we can make a trait that test if a type T is implicitly constructible from a pack Args (i.e. a brace-init-list of Args can be implicitly deduced as T) : 

```cpp
template <class T>
struct nested {
    T value;
};

template <class T, class... Args>
inline constexpr bool implicit_constructible = 
    requires (Args... args) { nested<T>{ {args...} }; };
```

(the standard library doesn't have that, AFAIK) 
So the second conversion becomes : 

```cpp
template <class T>
    requires std::is_constructible_v<T, Ts...>
explicit(not implicit_constructible<T, Ts...>) constexpr operator T();
```

Here's a godbolt to test that : 
https://godbolt.org/z/4EjW5K5fT

**Comment by jfalcou** [comment]
I did some tests and comparisons with `std::tuple` which, IMHO, we should be compatible with.
  - Conversion to std::tuple of references is not allowed, so I guess we should not allow them too, that's a job for another function or for structured bindings
  - tuple don't narrow on conversion, so we should slip a `static_cast<Us>(elems)...` in the conversion operator

**Comment by jfalcou** [comment]
Last version is OK for reviewing @groundswellaudio
