### ISSUE TITLE
[BUG] kumi::map for a struct inheriting from kumi::tuple does not compile

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/ofw#45]
Reproduction on godbolt: https://gcc.godbolt.org/z/Ms66T4vWP

Personally, I would maybe prefer if this returned a `smth` and not a `kumi::tuple`.
Regardless, should compile.

**Comment by jfalcou** [comment]
Issue is that the map result is not compatible with th original tuple like struct.
More over smth needs an explicit constructor from kumi::tupel to work properly.
